### ISSUE TITLE
Homepage button is on line 2, spilling over to line 3

### ISSUE THREAD

**Issue by dgutov** [laynor/melpa-upstream-visit#3]
This seems to depend on the window configuration.
Here are two screenshots from the same Emacs session (good and bad), the only difference seems to be the window position (not even width):
http://bayimg.com/kaNBDAAeb
http://bayimg.com/kAnBFaaeB

All default settings (in this package, at least).

**Comment by laynor** [comment]
Hi, and thanks for reporting :-)
The problem arises when the package list window is the only one opened. 
There are also other situations in which something similar happens, for example:
from a window that has `linum-mode` activated:

`M-x describe-package RET some-package RET`

The button will appear n characters before its expected position, where n is the width of the line numbers column.

About the situation you reported, the window width is calculated on the single list packages window spanning the whole frame, thus the bug.

By the way, meanwhile you can customize muv:button-location and set it to package-name if you prefer

I will look into this, thanks :-)

**Comment by laynor** [comment]
Fixed in commit cd4dd22.

**Comment by dgutov** [comment]
Thanks, it works fine now.
